### ISSUE TITLE
Chapter 3 bug?

### ISSUE THREAD

**Issue by aisflat439** [PacktPublishing/Building-Slack-Bots#1]
I'm following along and enjoying the book. I'm also learning a lot thanks to your hard work. I'm rather new to node so this could have nothing to do with a bug and everything to do with my mistake. 

`let Bot = require('./Bot');`

would not run without producing 

```
module.js:472
    throw err;
    ^

Error: Cannot find module './Bot'
```

Instead I used `let Bot = require('./bot');`

My system is running node `v7.4.0`.

**Comment by changux** [comment]
Anyone here?

**Comment by amritpandey23** [comment]
Hey @aisflat439 it is giving an error because there is no file with name `Bot`, the filename is `bot`

so

```
const Bot = require('./bot')
```

this will work!

**Comment by techsachinkumar** [comment]
Fixed !
