### ISSUE TITLE
chapter 2: TypeError

### ISSUE THREAD

**Issue by kskashyap94** [PacktPublishing/Building-Slack-Bots#4]
Seeing the error message "TypeError: MemoryDataStore is not a constructor" when "dataStore: new MemoryDataStore() is called" . I'm using the same code provided on github. what's the reason for this error ?

**Comment by amritpandey23** [comment]
Have you required `MemoryDataStore`?
```js
const MemoryDataStore = require('@slack/client').MemoryDataStore;
```

If you have, please paste in your own code here for a better idea about the situation.

**Comment by kskashyap94** [comment]
[index.txt](https://github.com/PacktPublishing/Building-Slack-Bots/files/1832942/index.txt)

Attaching my JS file as .txt file

**Comment by amritpandey23** [comment]
So, the code given in the github tutorial is based on older version of `slack API`.
According to version `4.0.1`, usage of default settings in `RtmClient` is deprecated.

Check the new method to connect to Slack here:
https://github.com/slackapi/node-slack-sdk/tree/v4.0.1#posting-a-message-with-the-real-time-messaging-api

They have actually made much easier to connect and watch for events now.

**Alternatively**:
You can install older version of api with:
`npm install --save @slack/client^3.15.0`

But this is not recommended.
